blank_issues_enabled: false
contact_links:
    - name: Documentation
      url: https://github.com/jinesis-app/.github-private/blob/main/docs/CONTRIBUTING.md
      about: Please read the documentation before creating an issue.
